### ISSUE TITLE
Introduce an argument on the Listener constructors to submit Properties for TJWS

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java-listener#24]
TJWS is configured using a Java properties object. Right now there isn't anyway to pass in configuration data to TJWS which means one can't do things like set up SSL config. So can we please introduce a new argument to the constructors to let the user pass in a TJWS property object?

**Comment by hideki** [comment]
TJWS property is configurable since https://github.com/couchbase/couchbase-lite-java-listener/pull/58 is merged. I will close this ticket.
