### ISSUE TITLE
Please support listening on whatever port is available

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java-listener#26]
Currently the Listener will try to get the port that was requested and otherwise will look around trying to find a free port. There are actually race conditions in the current code such that the Listener, when it tests if a port is free, sees that it is but before it can grab it the port can be taken at which point the Listener will fail.

A more robust solution is to set up the Listener to just grab whatever port happens to be free. This feature is supported in Java by specifying the port to listen to as '0'.

Making this work requires a number of changes:
- Delete LiteListener.discoverEmptyPort
- Change the LiteListener constructor to just take port specified (whatever value it is) and to either open that value or fail (in the case of 0 a failure means there are no free ports anywhere available)
- Implement #25 or equivalent and make it available for discovering the port that was selected

**Comment by NitzDKoder** [comment]
@hideki What is the latest plan on android? Pls confirm..

**Comment by hideki** [comment]
Following document also cover how to change listener port.
http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/tech-notes/p2p-replications-ssl/index.html
