### ISSUE TITLE
Introduce LiteSSLAcceptor

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java-listener#28]
This is a version of the SSLAcceptor class used by TJWS to handle a few different things. It would be implemented by inheriting from SSLAcceptor and implementing LiteAcceptor per #27.

But there are a few other things I would also like it to do. Specifically:
- So SSLAcceptor.ARG_PORT and Server.ARG_PORT aren't the same. This actually makes sense because there is an acceptor for TJWS that simultaneously supports HTTPS and HTTP. But LiteSSLAcceptor would only support HTTP over SSL. So I want to set the logic so that if Server.ARG_PORT is set but SSLAcceptor.ARG_PORT isn't then we will use Server.ARG_PORT.
- The same situation exists with SSLAcceptor.IFADDRESS and Serve.ARG_BINDADDRESS. I want to use the same solution.

**Comment by NitzDKoder** [comment]
@hideki What is the latest plan on Android? Pls confirm..

**Comment by hideki** [comment]
Hi @NitzDKoder 
You can refer following document.
http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/tech-notes/p2p-replications-ssl/index.html
