### ISSUE TITLE
Display image attachment in phonegap Android

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-listener#54]
From https://groups.google.com/d/msg/mobile-couchbase/rmkUou63Jlc/jKZJL2JgoVAJ

Displaying and image attachment using phonegap should be very simple as you could use a 

```
<img src="http://localhost:<port>/<database>/<docid>/<attachmentname" />
```

To display an attachment image..

Unfortunately, as Couchbase Lite on android requires basic authentication to be accessed by http requests , this will fail with a 401 error. Basic Auth can be done easily using ajax but in this case it is the webview issuing directly the HTTP request to get the image.. So how can we set up the basic Auth crendentials ?

**Comment by tleyden** [comment]
@jchris do you know if TodoLite-Phonegap does anything in particular to avoid this issue when being run  with Android?

**Comment by tleyden** [comment]
@jchris it's supposed to be showing images on this screen, right?  (most of these entries have images)

![screen shot 2015-01-08 at 3 50 46 pm](https://cloud.githubusercontent.com/assets/296876/5673268/36cc8fe2-974e-11e4-8f65-13ffbcdd0565.png)

**Comment by jchris** [comment]
I'm not seeing images in iOS, so I'm guessing there's an issue in TodoLite. Next step is to make sure TodoLite PhoneGap on iOS displays the images saved by native ToDo Lite. Once we have that, my hope is that they "just work" on Android, and provide a cross platform way to illustrate how to link to images or other attachments.

**Comment by jchris** [comment]
I filed an issue here https://github.com/couchbaselabs/TodoLite-PhoneGap/issues/17

**Comment by jchris** [comment]
After fixing the application bug the images are working great on Android. It's worth noting that the img src URL needs to include the basic auth credentials in the form `http://user:pass@host:port/dbname/docid/attachment.file`
