### ISSUE TITLE
Implement Digest Auth

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-listener#56]
CB Lite Listener on iOS uses Digest authentication. See this method in CocoaHTTPServer that CB Lite Listener iOS depends on https://github.com/couchbaselabs/CocoaHTTPServer/blob/3fbeb3faf0d3f6c8d1e9ad050bc46d43fbbffd63/Core/HTTPConnection.m#L375-L390.

Currently, the cb-lite-java-listener implements basic auth https://github.com/couchbase/couchbase-lite-java-listener/blob/master/src/main/java/com/couchbase/lite/listener/LiteServlet.java#L152-L185

Implementing digest auth would enable authed P2P replication between iOS and Android for apps such as [Photo Drop](https://github.com/couchbaselabs/photo-drop) and provide security enhancements for PhoneGap apps (see issue https://github.com/couchbase/couchbase-lite-java-listener/issues/48)

Gist that might help to implement digest auth https://gist.github.com/slightfoot/5624590

**Comment by NitzDKoder** [comment]
@hideki What is the latest plan on android? Pls confirm..

**Comment by hideki** [comment]
Duplicated with https://github.com/couchbase/couchbase-lite-java-listener/issues/56

**Comment by NitzDKoder** [comment]
@hideki is this in android? pls confirm...

**Comment by hideki** [comment]
@NitzDKoder 
Not yet implemented with Android
