### ISSUE TITLE
Large amount of response data causes deadlock

### ISSUE THREAD

**Issue by fpum** [couchbase/couchbase-lite-java-listener#57]
I'm running Couchbase Lite version: 1.1.0-532 (bug seems to be present in older versions as well).

When the response to a request contains a large amount of data, a deadlock occurs. This is caused by using PipedInputStream and PipedOutputStream in com.couchbase.lite.router.URLConnection. These are designed to be used on separate threads. If their internal buffer is full, writing to the output stream is blocked until another thread reads from the input stream. The LiteServlet and Router classes however use them on the same thread which causes a deadlock if the response data is large enough to fill the buffer.

**Comment by fpum** [comment]
This seems to only happen when requesting longpoll or continuous changes feeds (when there are many changes) because do_GET_Document_changes() in Router writes directly to the PipedOutputStream whereas the other methods set their response data using URLConnection.setResponseBody().

**Comment by hideki** [comment]
Hi @fpum,
Thank you very much for your bug report.
Could you please share your test environment and how to reproduce the issue?
Are you  using Listener module through PhoneGap plugin?
Thanks!

**Comment by fpum** [comment]
Hi @hideki,
I don't use the PhoneGap plugin. I have a HTML/JS frontend running in a WebView and some background services written in Java that are listening to changes in the database . Because most of this code is also used in a desktop environment using Apache CouchDB the frontend and the Java based backend access the database using the REST API. The LiteListener is started in my own Android service.

To reproduce the issue generate many changes in a database and try to request a continuous changes feed. I created a little demo app: https://github.com/fpum/deadlockdemo
It basically runs a loop from 1 to 1000 that in each iteration creates and deletes a new document and tries to get the changes using a continuous feed. You would expect it to run till "Created change number 1000" and "Found 1000 changes" but it gets stuck on the way.

**Comment by hideki** [comment]
Hi @fpum,
Thank you for your demo app and additional information. We will look  into the issue.
Please give us the time to figure out the problem.
Thanks!
Hideki

**Comment by fpum** [comment]
Hi @hideki,
I made a pull request to couchbase-lite-java-core that fixes this bug. See issue 667 and pull request 668 at couchbase-lite-java-core.

Best regards,
Florian
