### ISSUE TITLE
When replication resumes _active_tasks still returns a 400 error

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-listener#61]
When the app goes offline and returns online, the replication resumes and docs are replicated. But the `_active_tasks` endpoint on the listener still returns the error as shown below, as if the app was still offline. The `_active_tasks` endpoint is often used in apps built with the Listener API to display a connection status indicator. And the `error` property in the response can be used to show that sync is currently paused/offline.

This can be reproduced with liteserv-android (kick off continuous replication, check `_active_tasks` response, go offline or stop sync gateway, go back online, check `_active_tasks` and replication should resume). 

```
$ curl 'http://localhost:5984/_active_tasks'
```

```
[
 {
  "source":"http://localhost:4984/sync_gateway",
  "task":"repl002",
  "status":"Idle",
  "progress":100,
  "continuous":true,
  "target":"cblite-test",
  "error":
    [
      400,
      "org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:4984 refused"
    ],
    "type":"Replication"
  }
]
```

**Comment by hideki** [comment]
Hi @jamiltz,

I tested with following condition. So far, I could not reproduce the issue.

Device: Nexus 6
Client: curl command form OSX

1. Installed LiteServAndroid with CBL 1.2.0. 
2. Start replicator on device
```
cur-X POST --data '{"create_target":true, "source":"http://demo-mobile.couchbase.com/grocery-sync/","target":"db","continuous":true}' --header "Content-Type:application/json" "http://10.0.0.3:5984/_replicate"
```
Response
```json
{"session_id":"repl002"}
```
3. Call `/_active_tasks` 
```
curl "http://10.0.0.3:5984/_active_tasks"
```
Response
```json
[{"completed_change_count":0,"source":"http://demo-mobile.couchbase.com/grocery-sync/","task":"repl002","status":"Idle","progress":0,"continuous":true,"target":"db","change_count":0,"type":"Replication"}]
```
4. Make device Airplane mode for more than 5min (As DefaultSocketTime is 5min)
5. Call `/_active_tasks` 
```
curl "http://10.0.0.3:5984/_active_tasks"
```
Response
```json
[{"completed_change_count":0,"source":"http://demo-mobile.couchbase.com/grocery-sync/","task":"repl002","status":"Idle","progress":0,"continuous":true,"target":"db","change_count":0,"type":"Replication"}]
``` 

NOTE1: I can not see `error` section in response json
NOTE2: I observed SocketException in console for LiteServ

**Comment by jamiltz** [comment]
Ok I will try to reproduce again and let you know the results. I'm wondering what's the expected value in the `error` property of the response. Is it the current error if the replication is failing?

**Comment by hideki** [comment]
`error` is actually `lastError`. `Replicator` could hold `lastError` even though currently  replicator is running fine. `error` might not indicate current status.

**Comment by jamiltz** [comment]
Ok then this is the behaviour I observed. I was thinking of using it as a health check status for the connection. I'll close the issue. Thanks!
