### ISSUE TITLE
Simultaneous requests can sometimes lock the listener

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-listener#62]
It's a difficult issue to reproduce and I haven't been able to make a sample project to help find what's causing it.

It was tested with SQLite storage type and CBL Android 1.2.0-26. 

However, the zip file at http://cl.ly/0s3a3i3d3C1A contains:

- A screenshot of the Network debugging tab in Chrome when the issue starts happening. A lot of requests are in a pending state.
- Multiple thread dumps.

The same test was done by replacing the filter on the changes feed requests (for example, `/_changes?filter=orders/order...`) with requests to the view endpoints (for example `/_design/orders/_view/order`) and the issue remains.

Is there something that could cause the Listener to have multiple requests pending? What happens if multiple requests hit _changes at the same time? If part of the code is not thread safe and each request creates a new thread, could it then be in a locked state?

This locked state could be reproduced most of the time when the replication between devices was interrupted. When the replication resumed, the pending requests returned 200 and the application resumed. I'm wondering if the replications resuming could have an impact in triggering the pending requests to return.

**Comment by jamiltz** [comment]
I realize that's a lot of questions in one go, I wrote down the observations from testing the application in different scenarios.

**Comment by jamiltz** [comment]
Note: the files in the zip were taken from testing the app without replications, only requests to the Listener on localhost. The issue happens with or without replications. But, in the test with replications, it would eventually unblock the app and it would become responsive again. The moment the replicator inserts records to the database it triggers the pending HTTP requests over localhost to return.

**Comment by jamiltz** [comment]
It looks like this issue (https://github.com/couchbase/couchbase-lite-java-listener/issues/57). But I'm not sure.

**Comment by hideki** [comment]
Hi @jamiltz,
From current information, I am not sure where error is. So I will fix #57 first. Then, can you verify if fix for #57 also fixes this issue too?
Thanks,
Hideki

**Comment by jamiltz** [comment]
Ok sounds good. Yes of course I'll try with the fix from #57 first.

**Comment by hideki** [comment]
@jamiltz,
As I merged PR for #57, I will close this ticket.
if #62 and #57 is different issue, please reopen this?
Thanks!
