### ISSUE TITLE
1.2.1 Listener reporting invalid number

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-listener#68]
Using LiteServ Android targeting 1.2.1-2, I issue the following request:

```
GET http://XXX.XX.X.XX:10000/
```
The response returns the following invalid version number.
```
{"couchdb":"Welcome","CBLite":"Welcome","version":"1.2.1--1"}
```

Expected:
```
{"couchdb":"Welcome","CBLite":"Welcome","version":"1.2.1-2"}
```

Actual:
```
{"couchdb":"Welcome","CBLite":"Welcome","version":"1.2.1--1"}
```

**Comment by hideki** [comment]
Fixed this issue with following PR.
https://github.com/couchbase/couchbase-lite-java-core/pull/1168

**Comment by hideki** [comment]
duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/1153
